#数据源配置 MyBatisConfig.class
spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:3306/song88?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: jianjianhe2020
  redis:
    database: 14
    host: 192.168.1.106
    password:
    port: 6379

dubbo:
  registry:
    address: 127.0.0.1:2181
