#数据源配置 MyBatisConfig.class
spring:
  datasource:
    url: jdbc:mysql://192.168.233.133:3306/song88?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Aa123456
  redis:
    database: 0
    host: 192.168.233.133
    password:
    port: 6379

dubbo:
  registry:
    address: 192.168.233.133:2181
